export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const SET_USERINFO = 'SET_USERINFO';

export const GET_ALL_RESEARCHTYPES = 'GET_ALL_RESEARCHTYPES';
export const SET_PROPOSAL_GENERALINFO = 'SET_PROPOSAL_GENERALINFO';

export const SET_FILE = 'SET_FILE';

export const SEND_PROPOSAL = 'SEND_PROPOSAL';

export const GET_PROPOSAL = 'GET_PROPOSAL';
export const DELETE_PROPOSAL = 'DELETE_PROPOSAL';
export const GET_WAITING_PROPOSAL = 'GET_WAITING_PROPOSAL';
export const SET_PROFESSOR_CARTABLE_ERROR_MASSAGE = 'SET_PROFESSOR_CARTABLE_ERROR_MASSAGE';
export const SEND_PROPOSAL_FOR_ACTION = 'SEND_PROPOSAL_FOR_ACTION';
